/**
 * Generates an array of a specified length, populating each element using the provided repeator function.
 *
 * @param length - The length of the array to be generated.
 * @param repeator - A function that returns a value of type T based on the current index.
 * @returns An array of length `length` with each element generated by the repeator function.
 */
export function repeat<T>(length: number, repeator: (index: number) => T) {
	return Array.from({ length }).map((_, i) => repeator(i));
}
